server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ClientsDB
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

